export { ComplianceHeader } from './views/ComplianceHeader';
export { GeneralDataForm } from './views/GeneralDataForm';
export { CompliancePagination } from './views/CompliancePagination';
export { PreparatoryActsForm } from './views/PreparatoryActsForm';
export { PresentationOpeningActsForm } from './views/PresentationOpeningActsForm';
export { EvaluationQualificationForm } from './views/EvaluationQualificationForm';
export { FormalitiesAndArchiveForm } from './views/FormalitiesAndArchiveForm';
export { AdvancedReportForm } from './views/AdvancedReportForm';
export { AwardContractForm } from './views/AwardContractForm';
export { ComplianceProvider, useCompliance } from './context/ComplianceContext';
